#!/bin/bash

function send {
    screen -S stack -X stuff "$1"
    sleep 0.03
}


#export PATH=~/otp/bin:$PATH
export PATH=/home/matsw/Kreditor/svn/OTP/install/R13B04/bin:$PATH

send $'\003'
send $'a\n'
send $'clear\n'
send $"$(cat history)"
send $'\n'

